In [4]:
import cv2
import numpy as np
from keras.models import load_model
from skimage.transform import resize

In [5]:
model = load_model('../as1png.h5')

In [6]:
def detect(frame):
    img = resize(frame, (64, 64, 1))
    img = np.expand_dims(img, axis = 0)
    if(np.max(img) > 1):
        img = img/255.0
    prediction = model.predict(img)
    print(prediction)
    prediction = (model.predict(img) > 0.5).astype('int32')
    print(prediction)

In [9]:
frame = cv2.imread(r'./Datasets/test_sets/A/108.png')
data = detect(frame)

1/1 [==============================] - 0s 36ms/step
[[9.9968159e-01 3.0091498e-12 2.4218688e-10 3.5043505e-12 3.1718318e-04
  6.7085704e-10 6.2881168e-07 2.5672009e-07 4.0906860e-07]]
1/1 [==============================] - 0s 31ms/step
[[1 0 0 0 0 0 0 0 0]]


In [10]:
frame = cv2.imread(r'./Datasets/test_sets/B/15.png')
data = detect(frame)

1/1 [==============================] - 0s 35ms/step
[[2.7618323e-09 9.9993634e-01 1.8754812e-06 1.2471174e-06 5.4558855e-05
  1.0674579e-06 9.1501634e-10 5.5282865e-08 4.9394116e-06]]
1/1 [==============================] - 0s 31ms/step
[[0 1 0 0 0 0 0 0 0]]


In [11]:
frame = cv2.imread(r'./Datasets/test_sets/C/24.png')
data = detect(frame)

1/1 [==============================] - 0s 38ms/step
[[1.3005273e-14 1.7619950e-06 9.9985850e-01 6.0443241e-11 2.5366196e-06
  1.0765740e-07 1.3710307e-04 2.2931329e-12 1.5103675e-08]]
1/1 [==============================] - 0s 34ms/step
[[0 0 1 0 0 0 0 0 0]]
